### ISSUE TITLE
Tree/Partition area label should be "NIST SP 800-53 Coverage"

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall#50]
Tree/Partition area label should be "NIST SP 800-53 Coverage", not "Controls"

**Comment by lukemalinowski** [comment]
Line 111 of app/views/evaluations/_treemap.html.erb makes it complicated to inline SVGs.

``` js
109   function drawTreemap(category, status) {
110     console.log("drawTreemap");
111     d3.selectAll("svg").remove();
```

Here's what it would roughly look like...

<img width="1640" alt="Screen Shot 2019-08-09 at 7 44 25 AM" src="https://user-images.githubusercontent.com/40170735/62776819-a4c9ab80-ba79-11e9-810d-b7ef06d6f723.png">

The alternative we should go with for now is to use a PNG; since that doesn't require modifying the js for treemap.
